Repository microsoft/mu_tiano_plus, pull requests merged in 2023-01, with the labels that each got.

#76 Convert line endings from LF to CRLF
  EmbeddedPkg/Library/FdtLib/Makefile.libfdt
  EmbeddedPkg/Library/FdtLib/TODO
  EmbeddedPkg/Library/FdtLib/version.lds
  FmpDevicePkg/Test/UnitTest/Library/FmpDependencyLib/FmpDependencyLibUnitTestApp.inf
  RepoDetails.md
  SecurityPkg/Library/AuthVariableLib/AuthVariableLib.inf
  SecurityPkg/Library/DxeTcg2PhysicalPresenceLib/DxeTcg2PhysicalPresenceLib.inf
  SecurityPkg/Library/DxeTcg2PhysicalPresenceLib/PhysicalPresenceStrings.uni
  SecurityPkg/Library/DxeTcg2PhysicalPresenceMinimumLib/DxeTcg2PhysicalPresenceMinimumLib.inf
  SecurityPkg/Library/FmpAuthenticationLibPkcs7/FmpAuthenticationLibPkcs7.inf
  SecurityPkg/Library/MmTcg2PhysicalPresenceMinimumLib/StandaloneMmTcg2PhysicalPresenceMinimumLib.inf
  SecurityPkg/Library/MmTcg2PhysicalPresenceMinimumLib/TraditionalMmTcg2PhysicalPresenceMinimumLib.inf
  SecurityPkg/Library/OemTpm2InitLibNull/OemTpm2InitLib.inf
  SecurityPkg/Library/OemTpm2InitLibNull/OemTpm2InitLibVendorNull.inf
  SecurityPkg/Library/PlatformPKProtectionLibVarPolicy/PlatformPKProtectionLibVarPolicy.inf
  SecurityPkg/Library/SecureBootVariableLib/UnitTest/MockPlatformPKProtectionLib.inf
  SecurityPkg/Library/SecureBootVariableLib/UnitTest/MockUefiLib.inf
  SecurityPkg/Library/SecureBootVariableLib/UnitTest/MockUefiRuntimeServicesTableLib.inf
  SecurityPkg/Library/SecureBootVariableLib/UnitTest/SecureBootVariableLibUnitTest.inf
  SecurityPkg/Library/Tcg2PhysicalPresencePromptLib/Tcg2PhysicalPresencePromptLibConsole.inf
  SecurityPkg/Library/TempPreUefiEventLogLib/TempPreUefiEventLogLib.inf
  SecurityPkg/Library/Tpm2DebugLib/Tpm2DebugLibNull.inf
  SecurityPkg/Library/Tpm2DebugLib/Tpm2DebugLibSimple.inf
  SecurityPkg/Library/Tpm2DebugLib/Tpm2DebugLibVerbose.inf
  SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpm.inf
  SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpmStandaloneMm.inf
  SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2InstanceLibDTpm.inf
  SecurityPkg/Tcg/Tcg2Acpi/Tcg2Acpi.inf
  SecurityPkg/Tcg/Tcg2Acpi/Tpm.asl
  SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.inf
  SecurityPkg/Tcg/Tcg2PlatformDxe/Tcg2PlatformDxe.inf
  SecurityPkg/Test/SecurityPkgHostTest.dsc
  SourceLevelDebugPkg/Library/SourceDebugEnabled/SourceDebugEnabledLib.inf
  SourceLevelDebugPkg/Library/SourceDebugForceEnabled/SourceDebugForceEnabledLib.inf
Labels: impact:non-functional

#74 Updated repo readme to include changes that happened when updating to 202208
  ReadMe.rst
Labels: impact:non-functional, type:documentation

#59 Remove custom mode setting during PK deletion
  SecurityPkg/Library/SecureBootVariableLib/SecureBootVariableLib.c
  SecurityPkg/Library/SecureBootVariableLib/UnitTest/SecureBootVariableLibUnitTest.c
Labels: impact:security, impact:testing
