Repository microsoft/mu_tiano_plus, pull requests merged in 2023-02, with the labels that each got.

#87 .azurepipelines: Add support for new artifacts_identifier param
  .azurepipelines/Matrix-Build-Job.yml
Labels: type:enhancement, impact:breaking-change, impact:non-functional

#91 Remove VS2015 and VS2017 Stack Cookie Support from Package DSC Files
  EmbeddedPkg/EmbeddedPkg.dsc
  FatPkg/FatPkg.dsc
  FmpDevicePkg/FmpDevicePkg.dsc
  PrmPkg/PrmPkg.dsc
  SecurityPkg/SecurityPkg.dsc
  SourceLevelDebugPkg/SourceLevelDebugPkg.dsc
Labels: impact:non-functional

#93 Add CodeQL Stuart parameter to this repo
  .pytool/CISettings.py
Labels: type:enhancement, impact:non-functional

#96 SourceDebugPkg: Additional CodeQL fixes
  SourceLevelDebugPkg/Library/DebugAgent/SecPeiDebugAgent/SecPeiDebugAgentLib.c
  SourceLevelDebugPkg/Library/DebugCommunicationLibUsb3/DebugCommunicationLibUsb3Common.c
Labels: impact:security

#97 EmbeddedPkg: Additional CodeQL fixes
  EmbeddedPkg/Library/NonCoherentDmaLib/NonCoherentDmaLib.c
  EmbeddedPkg/Library/PrePiHobLib/Hob.c
  EmbeddedPkg/Library/PrePiLib/FwVol.c
  EmbeddedPkg/SimpleTextInOutSerial/SimpleTextInOut.c
Labels: impact:security

#98 FmpDevicePkg: Additional CodeQL fixes
  FmpDevicePkg/Library/FmpDependencyLib/FmpDependencyLib.c
Labels: impact:security

#95 SecurityPkg: Additional CodeQL fixes
  SecurityPkg/FvReportPei/FvReportPei.c
  SecurityPkg/HddPassword/HddPasswordDxe.c
  SecurityPkg/Library/AuthVariableLib/AuthService.c
  SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c
  SecurityPkg/Library/DxeTcgPhysicalPresenceLib/DxeTcgPhysicalPresenceLib.c
  SecurityPkg/Library/HashLibTdx/HashLibTdx.c
  SecurityPkg/Library/SecureBootVariableProvisionLib/SecureBootVariableProvisionLib.c
  SecurityPkg/Library/Tcg2PhysicalPresencePromptLib/Tcg2PhysicalPresencePromptLibConsole.c
  SecurityPkg/Library/TcgEventLogRecordLib/TcgEventLogRecordLib.c
  SecurityPkg/Library/Tpm12DeviceLibDTpm/Tpm12Tis.c
  SecurityPkg/Tcg/Opal/OpalPassword/OpalDriver.c
  SecurityPkg/Tcg/Opal/OpalPassword/OpalHii.c
  SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigDriver.c
  SecurityPkg/Tcg/TcgConfigDxe/TcgConfigImpl.c
  SecurityPkg/Tcg/TcgDxe/TcgDxe.c
  SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigFileExplorer.c
  SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c
Labels: impact:security
