Repository microsoft/mu_tiano_plus, pull requests merged in 2024-02, with the labels that each got.

#235 Added NULL implementation for Tcg2PreUefiEventLogLib
  SecurityPkg/Library/Tcg2PreUefiEventLogLibNull/Tcg2PreUefiEventLogLibNull.c
  SecurityPkg/Library/Tcg2PreUefiEventLogLibNull/Tcg2PreUefiEventLogLibNull.inf
  SecurityPkg/SecurityPkg.dsc
Labels: impact:non-functional

#236 Remove TempPreUefiEventLogLib since Tcg2PreUefiEventLogLibNull is available
  SecurityPkg/Library/TempPreUefiEventLogLib/TempPreUefiEventLogLib.c
  SecurityPkg/Library/TempPreUefiEventLogLib/TempPreUefiEventLogLib.inf
  SecurityPkg/SecurityPkg.dsc
Labels: impact:breaking-change

#224 Partial Revert "SecurityPkg/SecureBoot: Support RSA4096 and RSA3072"
  SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c
  SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigDxe.inf
  SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c
  SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.h
  SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigStrings.uni
Labels: impact:non-functional

#243 remove edk2-basetools
  .pytool/CISettings.py
  pip-requirements.txt
Labels: impact:non-functional

#245 [CHERRY-PICK] FatPkg/FatPei: Check array offset before use
  FatPkg/FatPei/FatLiteApi.c
Labels: impact:non-functional, semver:patch

#250 Corrects spelling error in unit test
  SecurityPkg/Library/DxeTpmMeasureBootLib/InternalUnitTest/DxeTpmMeasureBootLibSanitizationTest.c
Labels: impact:non-functional
