Repository microsoft/mu_tiano_plus, pull requests merged in 2024-07, with the labels that each got.

#297 SecurityPkg: Measure Invoke EBS even in failure case
  SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.c
Labels: impact:security

#299 FmpDevicePkg: Assert on PcdFmpDeviceImageTypeIdGuid Size Mismatch
  FmpDevicePkg/FmpDxe/FmpDxe.c
Labels: impact:non-functional

#301 FatPkg: Improvements to Fat to fix BCD corruption
  FatPkg/EnhancedFatDxe/DiskCache.c
  FatPkg/EnhancedFatDxe/Fat.h
Labels: type:bug

#300 FmpDevicePkg: Improve library documentation [Rebase & FF]
  FmpDevicePkg/CapsuleUpdatePolicyDxe/ReadMe.md
  FmpDevicePkg/Docs/FmpDevicePkg_ReadMe.md
  FmpDevicePkg/FmpDxe/ReadMe.md
  FmpDevicePkg/Library/CapsuleUpdatePolicyLibNull/ReadMe.md
  FmpDevicePkg/Library/CapsuleUpdatePolicyLibOnProtocol/ReadMe.md
  FmpDevicePkg/Library/FmpDependencyCheckLib/ReadMe.md
  FmpDevicePkg/Library/FmpDependencyCheckLibNull/ReadMe.md
  FmpDevicePkg/Library/FmpDependencyDeviceLibNull/ReadMe.md
  FmpDevicePkg/Library/FmpDependencyLib/ReadMe.md
  FmpDevicePkg/Library/FmpDeviceLibNull/ReadMe.md
  FmpDevicePkg/Library/FmpPayloadHeaderLibV1/ReadMe.md
  FmpDevicePkg/ReadMe.rst
Labels: impact:non-functional, type:documentation

#295 [CHERRY-PICK] SecurityPkg: Remove a debug statement that may cause a machine check.
  SecurityPkg/Tcg/Tcg2Acpi/Tcg2Acpi.c
Labels: impact:non-functional

#284 [Rebase & FF] 202405: Renaming shell test app in FmpDevicePkg
  FmpDevicePkg/FmpDevicePkg.dsc
  FmpDevicePkg/Test/UnitTest/Library/FmpDependencyLib/FmpDependencyLibUnitTestApp.inf
Labels: impact:breaking-change, impact:non-functional

#308 Require cspell 5.20.0 and apply fixes to all relevant files
  EmbeddedPkg/Drivers/AndroidFastbootTransportTcpDxe/FastbootTransportTcp.c
  EmbeddedPkg/Drivers/VirtualKeyboardDxe/VirtualKeyboard.c
  EmbeddedPkg/EmbeddedPkg.dec
  EmbeddedPkg/GdbStub/SerialIo.c
  EmbeddedPkg/Include/libfdt.h
  EmbeddedPkg/Library/AndroidBootImgLib/AndroidBootImgLib.c
  EmbeddedPkg/Library/VirtualRealTimeClockLib/VirtualRealTimeClockLib.c
  EmbeddedPkg/SimpleTextInOutSerial/SimpleTextInOut.c
  EmbeddedPkg/Universal/MmcDxe/MmcBlockIo.c
  SecurityPkg/Include/Library/OemTpm2InitLib.h
  SecurityPkg/Include/Library/PlatformPKProtectionLib.h
  SecurityPkg/Include/Library/Tpm2CommandLib.h
  SecurityPkg/Library/DxeTcg2PhysicalPresenceMinimumLib/DxeTcg2PhysicalPresenceMinimumLib.inf
  SecurityPkg/Library/DxeTpmMeasureBootLib/InternalUnitTest/DxeTpmMeasureBootLibSanitizationTest.c
  SecurityPkg/Library/OemTpm2InitLibNull/OemTpm2InitLib.c
  SecurityPkg/Library/PlatformPKProtectionLibVarPolicy/PlatformPKProtectionLibVarPolicy.c
  SecurityPkg/Library/SecureBootVariableLib/UnitTest/MockPlatformPKProtectionLib.c
  SecurityPkg/Library/SecureBootVariableLib/UnitTest/SecureBootVariableLibUnitTest.c
  SecurityPkg/Library/TcgEventLogRecordLib/TcgEventLogRecordLib.inf
  SecurityPkg/Library/Tpm2CommandLib/Tpm2Help.c
  SecurityPkg/Library/Tpm2CommandLib/Tpm2Hierarchy.c
  SecurityPkg/Library/Tpm2CommandLib/Tpm2Integrity.c
  SecurityPkg/Library/Tpm2CommandLib/Tpm2Sequences.c
  SecurityPkg/Tcg/Tcg2Acpi/Tcg2Acpi.c
  SecurityPkg/Tcg/Tcg2Pei/Tcg2Pei.c
  SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c
Labels: impact:non-functional

#282 EmbeddedPkg: Enable build under VS2019 and fix build errors.
  EmbeddedPkg/Library/GdbSerialDebugPortLib/GdbSerialDebugPortLib.c
Labels: impact:non-functional

#312 Cherry-pick forgotten TCG change.
  SecurityPkg/Tcg/Tcg2PlatformDxe/Tcg2PlatformDxe.c
  SecurityPkg/Tcg/Tcg2PlatformDxe/Tcg2PlatformDxe.inf
Labels: impact:breaking-change, impact:security, type:design-change
