Repository microsoft/mu_tiano_plus, pull requests merged in 2024-01, with the labels that each got.

#219 .git-blame-ignore-revs: Ignore Line Ending and Uncrustify only commits
  .git-blame-ignore-revs
Labels: impact:non-functional, semver:patch

#222 Removed references to OpensslLib and changed all instances of BaseCryptLib to be the NULL implementation
  FmpDevicePkg/FmpDevicePkg.ci.yaml
  FmpDevicePkg/FmpDevicePkg.dsc
  SecurityPkg/SecurityPkg.ci.yaml
  SecurityPkg/SecurityPkg.dsc
Labels: impact:non-functional

#230 Update pip-requirements.txt
  pip-requirements.txt
Labels: type:dependencies, impact:non-functional

#228 Updated CISettings.py to use the edk2toolext codeql helpers
  .github/workflows/codeql.yml
  .pytool/CISettings.py
Labels: impact:testing, impact:non-functional

#225 [Release/202302] SecurityPkg: SECURITY PATCH 4117 - 4118 CVE-2022-36763
  SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.c
  SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.inf
  SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLibSanitization.c
  SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLibSanitization.h
  SecurityPkg/Library/DxeTpm2MeasureBootLib/InternalUnitTest/DxeTpm2MeasureBootLibSanitizationTest.c
  SecurityPkg/Library/DxeTpm2MeasureBootLib/InternalUnitTest/DxeTpm2MeasureBootLibSanitizationTestHost.inf
  SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLib.c
  SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLib.inf
  SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLibSanitization.c
  SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLibSanitization.h
  SecurityPkg/Library/DxeTpmMeasureBootLib/InternalUnitTest/DxeTpmMeasureBootLibSanitizationTest.c
  SecurityPkg/Library/DxeTpmMeasureBootLib/InternalUnitTest/DxeTpmMeasureBootLibSanitizationTestHost.inf
  SecurityPkg/SecurityFixes.yaml
  SecurityPkg/SecurityPkg.ci.yaml
  SecurityPkg/Test/SecurityPkgHostTest.dsc
Labels: impact:security, impact:testing, impact:non-functional

#226 [Release/202311] SecurityPkg: SECURITY PATCH 4117 - 4118 CVE-2022-36763
  SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.c
  SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.inf
  SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLibSanitization.c
  SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLibSanitization.h
  SecurityPkg/Library/DxeTpm2MeasureBootLib/InternalUnitTest/DxeTpm2MeasureBootLibSanitizationTest.c
  SecurityPkg/Library/DxeTpm2MeasureBootLib/InternalUnitTest/DxeTpm2MeasureBootLibSanitizationTestHost.inf
  SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLib.c
  SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLib.inf
  SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLibSanitization.c
  SecurityPkg/Library/DxeTpmMeasureBootLib/DxeTpmMeasureBootLibSanitization.h
  SecurityPkg/Library/DxeTpmMeasureBootLib/InternalUnitTest/DxeTpmMeasureBootLibSanitizationTest.c
  SecurityPkg/Library/DxeTpmMeasureBootLib/InternalUnitTest/DxeTpmMeasureBootLibSanitizationTestHost.inf
  SecurityPkg/SecurityFixes.yaml
  SecurityPkg/SecurityPkg.ci.yaml
  SecurityPkg/Test/SecurityPkgHostTest.dsc
Labels: impact:security, impact:testing, impact:non-functional
